### ISSUE TITLE
Issue when system name contains repeating characters

### ISSUE THREAD

**Issue by onerok** [Stickymaddness/Sextant#1]
Systems that contain any repeating character result in an invalid search for the ‘find_next_system’ command because only one Key Press is registered.

For example “HIP 66560” will result in “HIP 6560” or “Ross 955” as “Ros 95”.

**Comment by Stickymaddness** [comment]
I haven't been able to replicate this, but have increased the keypress duration, I've uploaded a [testing version here](https://github.com/Stickymaddness/Sextant/releases/tag/1.0.1-Testing).

**Comment by onerok** [comment]
Still having the issue with the test build. I'll try to gather more information.

**Comment by TobiasPottgueter** [comment]
"Trappist-1" has the same Problem.

**Comment by Trentflix** [comment]
Using 1.0.1. same issue,

**Comment by Stickymaddness** [comment]
I'll look into this some more asap.

**Comment by kRAyZZed** [comment]
@Stickymaddness I seem to be getting this bug as well sadly. However I was hoping you might be able to add a work around? Would it be possible to add a feature/command for insert_next_system? and on triggering it pastes the name of the next system? So I can just get it to paste it into the search field whilst in VR?

My issue was multiple systems nearby all starting with HIP ... it didnt seem to want to pick one of them. Also using the most recent test build from here.

Great work btw, its really nice, and I can't wait to see where it goes next :D

**Comment by Stickymaddness** [comment]
I've released a new version of Sextant ([download here](https://github.com/Stickymaddness/Sextant/releases/tag/1.0.1)), with an overhauled input system. 

While I was not able to replicate the repeated character bug, this new input system should resolve the issue.
