### ISSUE TITLE
Expedition progress elapsed time

### ISSUE THREAD

**Issue by postfach** [Stickymaddness/Sextant#14]
When I use the expedition progress command, it tells me I've been going for something like 737000 days, is there a way I can fix this/edit the start time to get it a bit closer to what I've actually done?

**Comment by kaimi** [comment]
What version of VA are you running? I can’t even get mine to load the Sextant plugin because it’s too far out of date (read: not compatible with current VA).

**Comment by postfach** [comment]
> What version of VA are you running? I can’t even get mine to load the Sextant plugin because it’s too far out of date (read: not compatible with current VA).

1.7.7 (latest?) There is a check box in the general options tab to enable plugins - it worked after I checked that and restarted VA

**Comment by kaimi** [comment]
Huh. Guess I’ll have to double check if I’m running current Sextant.

**Comment by postfach** [comment]
Well, I finally had time to sit down and look at this properly, a file is created in the Voice Attack root folder called player_status.db - this contains your location, how much fuel you have, and the expedition start time/date.  You can open and edit it with [LiteDbExplorer](https://github.com/julianpaulozzi/LiteDbExplorer) - I had to run it as Administrator.
