### ISSUE TITLE
"No scans necessary in this system"

### ISSUE THREAD

**Issue by TobiasPottgueter** [Stickymaddness/Sextant#2]
It keeps telling my that i don't have to scan any celestial body in a system.

I'm using this Road to Riches: http://edtools.ddns.net/expl.php?s=Parutis&d=200&n=300&x=on

First part is: 
"  #   Jump System/Planets
--- ------ ---------------
  1  55.96 Trappist-1
	           4 (14) ELW
  2  76.07 ICZ FW-W c1-16
	           1 (457) TWW
  3  34.89 ICZ DB-X c1-18
	           1 (224) TWW
  4  82.36 Ehwaz
	           3 a (2390) TWW
...."

I'm arriving in Trappist-1 and use the "get_next_system" command, but i get "No scans necessary in this system".

**Comment by Stickymaddness** [comment]
Did everything import correctly when using plan_expedition?

**Comment by TobiasPottgueter** [comment]
yes, the import was ok.

**Comment by Stickymaddness** [comment]
Hmm, I might have to do some testing.

What does `next_scan` and `scans_remaining` give you? Have you tried using `rescan_system` ?

**Comment by TobiasPottgueter** [comment]
"plan_expedition" with [R2R Link](http://edtools.ddns.net/expl.php?s=Parutis&d=200&n=300&x=on) in clipboard results in:
"Expedition plotted. Route consists of 276 systems with 516 planets, In total there are 43 earth-like worlds, 260 water worlds and 213 high metal content worlds."

"find_next_system" searches for "Trapist-1" instead of "Trappist-1" (but that's covered in [Issue-1](https://github.com/Stickymaddness/Sextant/issues/1)

on jump to "Trappist-1":
"On route to Trappist-1. Surface scans are not required in this system."

in System "Trappist-1":
"rescan_system": 
"Surface scans are not required in this system."
"scans_remaining":
"We're just passing through here, No scans needed."
"skip_system":
"No surface scans are needed in this system."

hope that helps

**Comment by Stickymaddness** [comment]
Thanks for the details, it sounds like everything is working (other than Sextant not picking up the scans).

I'm going to import your expedition and jump over there to do some further testing. In the meantime if you want to "reset" everything and see if that helps, delete the"expedition.db" and "player_status.db" files in your VoiceAttack directory and try import a route again.

**Comment by Stickymaddness** [comment]
This has finally been fixed, a new release is [available here](https://github.com/Stickymaddness/Sextant/releases/tag/1.0.1)
