### ISSUE TITLE
HCS VoicePacks...

### ISSUE THREAD

**Issue by Commander-JAFO** [Stickymaddness/Sextant#5]
Hello,

Thank you for your excellent app! This really isn't an issue with your app but more of a question on how to use the HCS VoicePacks with your app. I see your example on the Wiki, but this appears to be more aimed at voices in Windows. Is there a way to use the HCS VoicePacks? I've experimented but none seem to work getting Eden (the voicepack I use) to work with your app.

Regards,
JAFO

**Comment by Stickymaddness** [comment]
Hi,

You won't be able to get HCS VoicePacks to work with Sextant as you've described, since the lines from Sextant are created as things happen and aren't prerecorded. 

The closest you'll get is using the Ivona Amy voice, which is the voice that was used for HCS Astra.

**Comment by Commander-JAFO** [comment]
Hello,

Yes...I was an idiot, don’t know what I was thinking. LOL That’s why I closed the ticket. It dawned on me later that the voice packs aren’t going to have pre-recorded system names and the like. A truly epic fail on my part.

Hopefully you got a chuckle out of it!

Regards,
JAFO
