### ISSUE TITLE
When a system has a ‘+’ sign in its name...

### ISSUE THREAD

**Issue by Commander-JAFO** [Stickymaddness/Sextant#6]
Hello,

I love this app! Makes my VR life so much easier, thank you!

Unfortunately I think I’ve found an issue. If a system has a ‘+’ sign in it (say like BD+02 305), the app will render it as BD=02 305 in the Galaxy Map search. It’s like the shift key isn’t being interpreted as ‘pressed’. This has happened every time a system with ‘+’ in it has been encountered.

Another issue was with system ‘Trappist-1’. The app would stall, for a lack of a better term, there and would not allow me past that system (all scanning was completed), even if I said to skip it. It would just continually say the next system was Trappist-1.

Regards,
JAFO

**Comment by Stickymaddness** [comment]
Glad to hear the app is making life easier for you!

Thanks for reporting the issue with BD+02 305, I'll look into a fix for this. You're actually the second person (See #2) to report the Trappist-1 issue, I'll get a fix out for this asap.

**Comment by Stickymaddness** [comment]
This has been fixed, please download the new release of Sextant, [available here](https://github.com/Stickymaddness/Sextant/releases/tag/1.0.1).

If you still encounter any further bugs, please open a new issue.
