### ISSUE TITLE
Macro keys are broken

### ISSUE THREAD

**Issue by Olexandr-Burdukovskii** [Stickymaddness/Sextant#7]
For me whenever i try "find_next_system" it fails 10/10 seemingly because some keys don't get pressed. Galaxy map sometimes will open, sometimes not. Then sometimes it will go to navigation tab, sometimes not. Once i was able to get system name entered when manually switching to nav tab. Overall it seems that keys aren't getting through. My educated guess is that game is polling keys approximately at it's FPS rate. Meaning that current sleep delay as seen in code (10) can slip through at 60fps (17ms gap). My guess is that since i might be getting even less than that, I'm getting astronomically low odds of completing full sequence.

Could you please make that sleep delay configurable?

P.S. Concept is great. I'd love to see it working for me!

**Comment by Stickymaddness** [comment]
I knew I should of made that 10ms configurable, I'll get something out asap.

**Comment by Stickymaddness** [comment]
I've added a new build that has the sleep delay configurable, I've dropped it down to 5ms in the settings file, please test and let me know.
