### ISSUE TITLE
Updated to 1.0.2, now Sextant won't...

### ISSUE THREAD

**Issue by Commander-JAFO** [Stickymaddness/Sextant#9]
I updated Sextant to v1.0.2 and now the plugin won't load into Voice Attack (v1.7.2). I get the following error with VA initializes:

"Plugin initialization exception: No registration for type ICommandExecutor could be found. Please note that the container instance you are resolving from contains no registrations. Could it be that you accidentally created a new -and empty- container?"

![capture2](https://user-images.githubusercontent.com/37963766/43363004-589c7f2e-92ae-11e8-95fe-857cf8418cd8.PNG)

Perhaps I've done something wrong but I can't find the issue.

**Comment by Stickymaddness** [comment]
Sounds like you're missing some of the files for Sextant, backup your current directory in VoiceAttack\Apps and delete it, then extract a new copy of 1.0.2, and copy over your settings from your backed up folder.
